id: IB5141195
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-12T14:51:42+00:00'
last_modified: '2022-06-15T15:24:14.413873+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28829
  title: དཔྱད་རྩོམ་ཚངས་པའི་ཐིག་རིས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    13AE:
      image_group_id: I5762
      title: ''
      total_pages: 578
      order: 1
      base_file: 13AE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
